# Generated by Django 4.2.16 on 2025-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlecomment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Изображение'),
        ),
    ]
