# Generated by Django 4.2.16 on 2025-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_poster_alter_articleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Постер'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
