# Generated by Django 4.2.16 on 2025-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_poster_delete_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Превью'),
        ),
    ]
