# Generated by Django 4.2.16 on 2025-04-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='article_tags',
        ),
    ]
