# Generated by Django 4.2.16 on 2025-04-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_tags_article_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_tags',
        ),
    ]
