# Generated by Django 4.2.16 on 2025-04-19 17:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('articles', '0008_remove_article_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
