# Generated by Django 4.2.16 on 2025-05-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
