# Generated by Django 4.2.16 on 2025-02-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help', '0002_remove_comment_helps_comment_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='questions',
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='help.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
