# Generated by Django 4.2.16 on 2025-05-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_alter_question_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос_пользователя', 'verbose_name_plural': 'Вопросы_пользователей'},
        ),
    ]
