# Generated by Django 4.2.16 on 2025-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('discussing', 'Обсуждается'), ('resolved', 'Решено')], default='discussing', max_length=20),
        ),
    ]
