# Generated by Django 4.2.16 on 2025-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='views',
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
