# Generated by Django 4.2.16 on 2025-05-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_review_views_alter_review_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
