# Generated by Django 4.2.16 on 2025-04-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='python_topic_scores',
            field=models.TextField(default='{}'),
        ),
    ]
