# Generated by Django 4.2.16 on 2025-04-19 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_eventuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='content',
        ),
        migrations.AddField(
            model_name='eventuser',
            name='template_name',
            field=models.CharField(default=None, max_length=200, verbose_name='Шаблон'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время показа')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventuser', verbose_name='Эвент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'event', 'timestamp')},
            },
        ),
    ]
