# Generated by Django 4.2.16 on 2025-04-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_article_tags'),
        ('main', '0004_remove_eventuser_content_eventuser_template_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventuser',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.article', verbose_name='Статья'),
        ),
    ]
