# Generated by Django 4.2.16 on 2025-04-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_eventuser_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='article',
        ),
        migrations.AddField(
            model_name='eventuser',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventuser',
            name='object_id',
            field=models.PositiveIntegerField(default=None, verbose_name='ID объекта'),
            preserve_default=False,
        ),
    ]
