# Generated by Django 4.2.16 on 2025-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_eventuser_article_eventuser_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_tasks_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление задач'),
        ),
    ]
