# Generated by Django 4.2.16 on 2025-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_last_tasks_update'),
        ('tasks', '0005_tasksweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.tasksweek', verbose_name='Задачи на неделю'),
        ),
    ]
