# Generated by Django 4.2.16 on 2025-05-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuser',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
    ]
