# Generated by Django 4.2.16 on 2025-05-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0009_alter_eventuser_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='event',
        ),
    ]
