# Generated by Django 4.2.16 on 2025-04-16 12:20

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tasks', '0002_tasklist_remove_task_description_remove_task_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
