# Generated by Django 4.2.16 on 2025-04-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_poster_remove_task_tags_tasklist_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=0, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
