# Generated by Django 4.2.16 on 2025-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasksweek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'verbose_name': 'Список_задач', 'verbose_name_plural': 'Списки_задач'},
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
    ]
