# Generated by Django 4.2.16 on 2025-06-05 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_question_reward_question_tags_test_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='usertestattempt',
            options={'ordering': ['-date_taken']},
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Очень легко'), (2, 'Легко'), (3, 'Средне'), (4, 'Сложно'), (5, 'Очень сложно')], default=3, verbose_name='Сложность вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='main_tag',
            field=models.CharField(default=None, max_length=15, verbose_name='Награда за правильный ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='max_questions',
            field=models.PositiveIntegerField(default=20, verbose_name='Максимальное количество вопросов'),
        ),
        migrations.AddField(
            model_name='test',
            name='min_questions',
            field=models.PositiveIntegerField(default=10, verbose_name='Минимальное количество вопросов'),
        ),
        migrations.AddField(
            model_name='test',
            name='retake_cooldown',
            field=models.PositiveIntegerField(default=21, verbose_name='Дней до пересдачи'),
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='details',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='max_score',
            field=models.FloatField(default=None, verbose_name='Максимальный балл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='score',
            field=models.FloatField(verbose_name='Набранный балл'),
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
