# Generated by Django 4.2.16 on 2025-06-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
    ]
