# Generated by Django 4.2.16 on 2025-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20250605_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(1, 'Очень легко'), (2, 'Легко'), (3, 'Средне'), (4, 'Сложно'), (5, 'Очень сложно')], default=3, verbose_name='Сложность вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_questions',
            field=models.IntegerField(default=20, verbose_name='Максимальное количество вопросов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='min_questions',
            field=models.IntegerField(default=10, verbose_name='Минимальное количество вопросов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='retake_cooldown',
            field=models.IntegerField(default=21, verbose_name='Дней до пересдачи'),
        ),
    ]
