# Generated by Django 4.2.16 on 2025-06-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_question_difficulty_alter_test_max_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestattempt',
            name='details',
        ),
    ]
